FS_PROJECT_ASPNETCore_WebTutorQuizzer/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace FS_PROJECT_ASPNETCore_WebTutorQuizzer.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FS_PROJECT_ASPNETCore_WebTutorQuizzer/Controllers/SubjectController.cs
using FS_PROJECT_ASPNETCore_WebTutorQuizzer.Data;
using FS_PROJECT_ASPNETCore_WebTutorQuizzer.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Text.Encodings.Web;

namespace FS_PROJECT_ASPNETCore_WebTutorQuizzer.Controllers
{
    public class SubjectController : Controller
    {
        private readonly DataContext dataContext;

        public SubjectController(DataContext dbContext)
        {
            dataContext = dbContext;    
        }

        public IActionResult Welcome(string name, int numTimes = 2)
        {
            ViewData["Message"] = "Hello" + name;
            ViewData["NumTimes"] = numTimes;
            return View();
        }

        // GET: SubjectController
        public IActionResult Index()
        {
            var subjects = dataContext.Subject.ToList();
            return View(subjects);
        }

        // GET: SubjectController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var subject = await dataContext.Subject
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // GET: SubjectController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SubjectController/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Title")] SubjectModel subject)
        {
            if (ModelState.IsValid)
            {
                dataContext.Subject.Add(subject);
                await dataContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            if (!ModelState.IsValid)
            {
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }
            return View(subject);
        }

        // GET: SubjectController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SubjectController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id", "Title")] SubjectModel subject)
        {
            if(id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
               dataContext.Update(subject);
               await dataContext.SaveChangesAsync();
               return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: SubjectController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SubjectController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FS_PROJECT_ASPNETCore_WebTutorQuizzer/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;

namespace FS_PROJECT_ASPNETCore_WebTutorQuizzer.Controllers
{
    public class TodoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FS_PROJECT_ASPNETCore_WebTutorQuizzer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="d-flex flex-nowrap" style="height: 100vh;">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 280px;">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                <span class="fs-4">Sidebar</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Home")" class="nav-link" aria-current="page">
                        Home
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Dashboard")" class="nav-link link-body-emphasis">
                        Dashboard
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Subject")" class="nav-link link-body-emphasis">
                        Subjects
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Todo")" class="nav-link link-body-emphasis">
                        ToDo Quiz
                    </a>
                </li>
            </ul>
            <hr>
            @*
            <div class="dropdown">
                 <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                     <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                     <strong>mdo</strong>
                 </a>
                 <ul class="dropdown-menu text-small shadow">
                     <li><a class="dropdown-item" href="#">New project...</a></li>
                     <li><a class="dropdown-item" href="#">Settings</a></li>
                     <li><a class="dropdown-item" href="#">Profile</a></li>
                     <li><hr class="dropdown-divider"></li>
                     <li><a class="dropdown-item" href="#">Sign out</a></li>
                 </ul>
            </div>
            *@
        </div>
        <div style="width: 20px;"></div>
        <div>
            @RenderBody()
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>